import sequelize from "../../database/database";
import { CreationOptional, DataTypes, InferAttributes, InferCreationAttributes, Model } from "sequelize";

import type { UserRole, UserStatus } from "./user.types";

/**
 * InferAttributes = getting all attributes of the User model
 * InferCreationAttributes = Identify which fields are required and which are optional when creating a user.
 * CreationOptional = Marking the id and role fields as optional when creating a new user, since they will be automatically generated by the database.
 */
class User extends Model<InferAttributes<User>, InferCreationAttributes<User>> {
    declare id: CreationOptional<number>;
    declare name: string;
    declare email: string;
    declare passwordHash: string;
    declare role: CreationOptional<UserRole>;
    declare status: CreationOptional<UserStatus>;
    declare createdAt: CreationOptional<Date>;
    declare updatedAt: CreationOptional<Date>;

}

/**
 * It connects the user class to the actual database table configuration.
 * This User.init is telling Sequelize that What are the database columns for this User model, and which table will it connect to? 
 */
User.init(
  {
    id: {
      type: DataTypes.INTEGER.UNSIGNED,
      allowNull: false,
      autoIncrement: true,
      primaryKey: true
    },

    name: {
      type: DataTypes.STRING(100),
      allowNull: false
    },

    email: {
      type: DataTypes.STRING(255),
      allowNull: false,
      unique: true
    },

    passwordHash: {
      type: DataTypes.STRING(255),
      allowNull: false,
      field: "password_hash"
    },

    role: {
      type: DataTypes.ENUM(
        "ADMIN",
        "STAFF",
        "CUSTOMER"
      ),
      allowNull: false,
      defaultValue: "CUSTOMER"
    },

    status: {
      type: DataTypes.ENUM(
        "ACTIVE",
        "INACTIVE"
      ),
      allowNull: false,
      defaultValue: "ACTIVE"
    },

    createdAt: {
      type: DataTypes.DATE,
      allowNull: false,
      field: "created_at"
    },

    updatedAt: {
      type: DataTypes.DATE,
      allowNull: false,
      field: "updated_at"
    }
  },

  {
    sequelize,
    tableName: "users",
    timestamps: true,
    underscored: true
  }
);

export default User;