import database from "../../database/database";
import { CreationOptional, InferAttributes, InferCreationAttributes, Model } from "sequelize";

import type { userRole, userStatus } from "./user.types";

/**
 * InferAttributes = getting all attributes of the User model
 * InferCreationAttributes = Identify which fields are required and which are optional when creating a user.
 * CreationOptional = Marking the id and role fields as optional when creating a new user, since they will be automatically generated by the database.
 */
class User extends Model<InferAttributes<User>, InferCreationAttributes<User>> {
    declare id: CreationOptional<number>;
    declare name: string;
    declare email: string;
    declare password_hash: string;
    declare role: CreationOptional<userRole>;
    declare status: CreationOptional<userStatus>;
    declare createdAt: CreationOptional<Date>;
    declare updatedAt: CreationOptional<Date>;

}

/**
 * It connects the user class to the actual database table configuration.
 */
// User.init({

// })